"@binstruct/arp":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/arp/**
"@binstruct/bmp":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/bmp/**
"@binstruct/cli":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/cli/**
"@binstruct/ethernet":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/ethernet/**
"@binstruct/icmp":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/icmp/**
"@binstruct/ipv4":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/ipv4/**
"@binstruct/pcap":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/pcap/**
"@binstruct/png":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/png/**
"@binstruct/udp":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/udp/**
"@binstruct/wav":
  - changed-files:
      - any-glob-to-any-file: packages/@binstruct/wav/**
"@hertzg/binstruct":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/binstruct/**
"@hertzg/bx":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/bx/**
"@hertzg/crc":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/crc/**
"@hertzg/inet":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/inet/**
"@hertzg/ip":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/ip/**
"@hertzg/mac":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/mac/**
"@hertzg/mymagti-api":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/mymagti-api/**
"@hertzg/routeros-api":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/routeros-api/**
"@hertzg/tplink-api":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/tplink-api/**
"@hertzg/wg-conf":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/wg-conf/**
"@hertzg/wg-ini":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/wg-ini/**
"@hertzg/wg-keys":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/wg-keys/**
"@hertzg/xhb":
  - changed-files:
      - any-glob-to-any-file: packages/@hertzg/xhb/**
