# Release configuration for conventional commits

types:
  feat: minor
  fix: patch
  chore: none

scopes:
  binstruct: true
  wg-keys: true
  wg-ini: true
  wg-conf: true
  mymagti-api: true
  bx: true

breaking:
  major: true

prerelease:
  enabled: false
  branches: []

notes:
  enabled: true
  template: |
    ## What's Changed

    {changes}

    ## Breaking Changes

    {breaking}

    ## Contributors

    {contributors}
